[package]
edition = "2018"
name = "example_elo"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "example_elo"

[dependencies]
derive_more = "0"
serde = "1"

hc_mixin_elo = {path = "../../../mixin"}
hdk = "0.0.115"
holo_hash = {version = "0.0.12", features = ["encoding"]}
